# config/subscriptions.yaml

# Global default fetch interval in seconds; can be overridden per subscription
# default_interval: 300

# List of RSS subscriptions
# Sample:
# feeds:
#   - id: [unique id]
#     name: [name]
#     url: [url]
#     category: [category]
#     tags: [tags]
#     interval: [interval]    # Individual fetch interval in seconds
#     enabled: [true/false]   # GUI can toggle this field to enable/disable the subscription

